In [2]:
m=[1 2 3; 4 5 6; 5 6 1; 2 3 7]

4×3 Array{Int64,2}:
 1  2  3
 4  5  6
 5  6  1
 2  3  7

In [3]:
goldcost=[0 1 3; 1 3 6; 5 8 12; 10 12 13]

4×3 Array{Int64,2}:
  0   1   3
  1   3   6
  5   8  12
 10  12  13

In [4]:
#0 = ner
#1 = höger
golddir=[9 1 1; 0 1 1; 0 1 1; 0 0 1]

4×3 Array{Int64,2}:
 9  1  1
 0  1  1
 0  1  1
 0  0  1

In [101]:
function hej(m)
    Y=size(m,1)
    X=size(m,2)
    dir=ones(Int,(Y,X))
    cost=zeros(Int,(Y,X))
    for x=1:X,y=1:Y
        if x>1
            cost[y,x]=cost[y,x-1]+m[y,x-1]
            dir[y,x]  = y==1 ? 1 : dir[y,x-1]
        end
        if y>1
            t_cost=cost[y-1,x]+m[y-1,x]
            if t_cost<cost[y,x] || x==1
                cost[y,x]=t_cost
                dir[y,x] = x==1 ? 0 : dir[y-1,x]
            end
        end
    end
    dir[1,1]=9
    return cost, dir
end

display.(hej(m))

4×3 Array{Int64,2}:
  0   1   3
  1   3   6
  5   8  12
 10  12  13

4×3 Array{Int64,2}:
 9  1  1
 0  1  1
 0  1  1
 0  0  1

(nothing, nothing)

In [102]:
display.((goldcost,golddir))

4×3 Array{Int64,2}:
  0   1   3
  1   3   6
  5   8  12
 10  12  13

4×3 Array{Int64,2}:
 9  1  1
 0  1  1
 0  1  1
 0  0  1

(nothing, nothing)

In [103]:
?circshift

search: circshift circshift!



```
circshift(A, shifts)
```

Circularly shift the data in an array. The second argument is a vector giving the amount to shift in each dimension.

```jldoctest
julia> b = reshape(collect(1:16), (4,4))
4×4 Array{Int64,2}:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

julia> circshift(b, (0,2))
4×4 Array{Int64,2}:
  9  13  1  5
 10  14  2  6
 11  15  3  7
 12  16  4  8

julia> circshift(b, (-1,0))
4×4 Array{Int64,2}:
 2  6  10  14
 3  7  11  15
 4  8  12  16
 1  5   9  13
```

See also [`circshift!`](@ref).


In [104]:
?flipdim

search: flipdim



```
flipdim(A, d::Integer)
```

Reverse `A` in dimension `d`.

```jldoctest
julia> b = [1 2; 3 4]
2×2 Array{Int64,2}:
 1  2
 3  4

julia> flipdim(b,2)
2×2 Array{Int64,2}:
 2  1
 4  3
```


In [105]:
min.(m,m)

4×3 Array{Int64,2}:
 1  2  3
 4  5  6
 5  6  1
 2  3  7

In [106]:
function replace!(x, KV::Pair{Int,Int}...)
    for (k,v) in KV
        x[x.==k] = v
    end
    x
end

replace! (generic function with 1 method)

In [107]:
q1(m) = flipdim(circshift(m, (-1,0)), 1)
q2(m) = q1(q3(m))
q3(m) = flipdim(circshift(m, (0,-1)), 2)
q4(m) = m

iq1(m,d) = q1(m), replace!(d, 0 => 2)
iq2(m,d) = q2(m), replace!(d, 0 => 2, 1 => 3)
iq3(m,d) = q3(m), replace!(d, 1 => 3)
iq4(m,d) = q4(m), d

iq4 (generic function with 1 method)

In [108]:
shiftorigin(m, origin) = circshift(M, (1-origin[1], 1-origin[2]))
ishiftorigin(m, origin) = circshift(m, (origin[1]-1, origin[2]-1))

shiftorigin (generic function with 1 method)

In [140]:
function travelcost(M, origin)
    m = shiftorigin(m, origin)
    expand(f) = x -> f(x...)
    c1,d1 = m |> q1 |> hej |> expand(iq1)
    c2,d2 = m |> q2 |> hej |> expand(iq2)
    c3,d3 = m |> q3 |> hej |> expand(iq3)
    c4,d4 = m |> q4 |> hej |> expand(iq4)
    
    D = cat(3, d1,d2,d3,d4)
    C = cat(3, c1,c2,c3,c4)
    v, i = findmin(C,3)
    
    C = ishiftorigin(C[i][:,:,1], origin)
    D = ishiftorigin(D[i][:,:,1], origin)
    
    return C, D
end

c, d = travelcost(m, [3,2])

([11 9 11; 11 6 7; 6 0 6; 9 6 7], [0 0 0; 2 2 2; 3 9 1; 0 0 1])

In [123]:
c = travelcost(m, [3,2])[1]

4×3 Array{Int64,2}:
 11  9  11
 11  6   7
  6  0   6
  9  6   7

In [141]:
# M is halite amount
function score(M, ship, shipyard, threshold)
    mining = max.(0, M - threshold)
    leftovers = min.(mining, threshold)
    ignoreshipyard = M[shipyard...]
    #travel = travelcost(M, ship) + travelcost(M, shipyard) + leftovers - ignoreshipyard
    #return mining - 0.1*travel
    cost1, direction1 = travelcost(0.1*M, ship)
    cost2, direction2 = travelcost(0.1*M, shipyard)
    
    cost = cost1 + cost2 + 0.1*leftovers - 0.1*ignoreshipyard
    direction = direction1
    
    score = mining - cost
    return score, direction
end

score (generic function with 1 method)

In [158]:
HALITE=m*10
ship = [4,3]
shipyard = [1,1]
threshold = 1
s, d = score(HALITE, ship, shipyard, threshold)

([0.9 8.9 21.9; 28.9 34.9 47.9; 38.9 45.9 -5.1; 11.9 19.9 66.9], [1 0 0; 1 0 2; 2 2 2; 1 3 9])

In [159]:
s

4×3 Array{Float64,2}:
  0.9   8.9  21.9
 28.9  34.9  47.9
 38.9  45.9  -5.1
 11.9  19.9  66.9

In [160]:
d

4×3 Array{Int64,2}:
 1  0  0
 1  0  2
 2  2  2
 1  3  9

In [161]:
HALITE

4×3 Array{Int64,2}:
 10  20  30
 40  50  60
 50  60  10
 20  30  70